# .github/workflows/ci.yml
name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest 
    permissions:
      # To comment on PRs
      pull-requests: write
      # To retrieve test step time in GitHub Action
      contents: read
      # To retrieve previous report/To delete current report  for default branch, which is saved as GitHub Action Artifacts
      actions: write
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      -
        name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out
      -
        uses: k1LoW/octocov-action@v1