name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build multi-platform
        run: |
          GOOS=linux GOARCH=amd64 go build -o gogoversion-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o gogoversion-windows-amd64.exe .
          GOOS=darwin GOARCH=arm64 go build -o gogoversion-macos-arm64 .

      - name: Crear Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gogoversion-linux-amd64
            gogoversion-windows-amd64.exe
            gogoversion-macos-arm64
          generate_release_notes: true
